Add table azure_data_factory_pipeline. Closes #151
turbot/steampipe-plugin-azure pull request #169
Opened 2021-07-05 10:06 UTC by rajeshbal65

# Integration test logs
<details>
  <summary>Logs</summary>
  
```
No env file present for the current environment:  staging 
 Falling back to .env config
No env file present for the current environment:  staging
customEnv TURBOT_TEST_EXPECTED_TIMEOUT 300

SETUP: tests/azure_data_factory_pipeline []

PRETEST: tests/azure_data_factory_pipeline

TEST: tests/azure_data_factory_pipeline
Running terraform
data.azurerm_client_config.current: Refreshing state...
azurerm_resource_group.named_test_resource: Creating...
azurerm_resource_group.named_test_resource: Creation complete after 3s [id=/subscriptions/********-****-****-****-************/resourceGroups/turbottest38586]
azurerm_data_factory.named_test_resource: Creating...
azurerm_data_factory.named_test_resource: Still creating... [10s elapsed]
azurerm_data_factory.named_test_resource: Still creating... [20s elapsed]
azurerm_data_factory.named_test_resource: Creation complete after 22s [id=/subscriptions/********-****-****-****-************/resourceGroups/turbottest38586/providers/Microsoft.DataFactory/factories/turbottest38586]
azurerm_data_factory_pipeline.named_test_resource: Creating...
azurerm_data_factory_pipeline.named_test_resource: Creation complete after 4s [id=/subscriptions/********-****-****-****-************/resourceGroups/turbottest38586/providers/Microsoft.DataFactory/factories/turbottest38586/pipelines/turbottest38586]

Warning: Deprecated Resource

The null_data_source was historically used to construct intermediate values to
re-use elsewhere in configuration, the same can now be achieved using locals

Apply complete! Resources: 3 added, 0 changed, 3 destroyed.

Outputs:

resource_aka = azure:///subscriptions/********-****-****-****-************/resourceGroups/turbottest38586/providers/Microsoft.DataFactory/factories/turbottest38586/pipelines/turbottest38586
resource_aka_lower = azure:///subscriptions/********-****-****-****-************/resourcegroups/turbottest38586/providers/microsoft.datafactory/factories/turbottest38586/pipelines/turbottest38586
resource_id = /subscriptions/********-****-****-****-************/resourceGroups/turbottest38586/providers/Microsoft.DataFactory/factories/turbottest38586/pipelines/turbottest38586
resource_name = turbottest38586
subscription_id = ********-****-****-****-************

Running SQL query: test-get-query.sql
[
  {
    "id": "/subscriptions/********-****-****-****-************/resourceGroups/turbottest38586/providers/Microsoft.DataFactory/factories/turbottest38586/pipelines/turbottest38586",
    "name": "turbottest38586",
    "resource_group": "turbottest38586",
    "subscription_id": "********-****-****-****-************"
  }
]
✔ PASSED

Running SQL query: test-list-query.sql
[
  {
    "id": "/subscriptions/********-****-****-****-************/resourceGroups/turbottest38586/providers/Microsoft.DataFactory/factories/turbottest38586/pipelines/turbottest38586",
    "name": "turbottest38586",
    "resource_group": "turbottest38586",
    "subscription_id": "********-****-****-****-************"
  }
]
✔ PASSED

Running SQL query: test-not-found-query.sql
null
✔ PASSED

Running SQL query: test-turbot-query.sql
[
  {
    "akas": [
      "azure:///subscriptions/********-****-****-****-************/resourceGroups/turbottest38586/providers/Microsoft.DataFactory/factories/turbottest38586/pipelines/turbottest38586",
      "azure:///subscriptions/********-****-****-****-************/resourcegroups/turbottest38586/providers/microsoft.datafactory/factories/turbottest38586/pipelines/turbottest38586"
    ],
    "name": "turbottest38586",
    "title": "turbottest38586"
  }
]
✔ PASSED

POSTTEST: tests/azure_data_factory_pipeline

TEARDOWN: tests/azure_data_factory_pipeline

SUMMARY:

1/1 passed.
```
</details>

# Example query results
<details>
  <summary>Results</summary>
  
```
### Basic info

```sql
select
  name,
  id,
  type,
  etag,
  factory_name
from
  azure_data_factory_pipeline;

+-----------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------+--------------------------------------+-----------------+
| name            | id                                                                                                                                                                     | type                                      | etag                                 | factory_name    |
+-----------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------+--------------------------------------+-----------------+
| turbottest44547 | /subscriptions/d7245080-b4ae-4fe5-b6fa-2e71b3dae6c8/resourceGroups/turbottest44547/providers/Microsoft.DataFactory/factories/turbottest44547/pipelines/turbottest44547 | Microsoft.DataFactory/factories/pipelines | 070074c7-0000-0100-0000-60e2d8650000 | turbottest44547 |
+-----------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------+--------------------------------------+-----------------+
```
```
select
  p.name,
  p.id,
  p.factory_name,
  f.encryption factory_encryption
from
  azure_data_factory_pipeline p,
  azure_data_factory f
  where f.encryption is null;
+-----------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------+--------------------+
| name            | id                                                                                                                                                                     | factory_name    | factory_encryption |
+-----------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------+--------------------+
| turbottest35948 | /subscriptions/d7245080-b4ae-4fe5-b6fa-2e71b3dae6c8/resourceGroups/turbottest35948/providers/Microsoft.DataFactory/factories/turbottest35948/pipelines/turbottest35948 | turbottest35948 | <null>             |
+-----------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------+--------------------+
```
</details>

2021-07-05 13:51 UTC, Subhajit97 commented on azure/table_azure_data_factory.go
> +//// TABLE DEFINITION ////
```suggestion
//// TABLE DEFINITION
```

2021-07-05 13:51 UTC, Subhajit97 commented on azure/table_azure_data_factory_pipeline.go
> +//// TABLE DEFINITION ////
```suggestion
//// TABLE DEFINITION
```

2021-07-05 13:51 UTC, Subhajit97 commented on azure/table_azure_data_factory_pipeline.go
> +			Hydrate:           getPipeline,
```suggestion
			Hydrate:           getDataFactoryPipeline,
```

2021-07-05 13:51 UTC, Subhajit97 commented on azure/table_azure_data_factory_pipeline.go
> +			Hydrate:       listPipelines,
```suggestion
			Hydrate:       listDataFactoryPipelines,
```

2021-07-05 13:52 UTC, Subhajit97 commented on azure/table_azure_data_factory_pipeline.go
> +				Name:        "factory_name",
Add this column after `id`

2021-07-05 13:52 UTC, Subhajit97 commented on azure/table_azure_data_factory_pipeline.go
> +				Description: "Time the factory was created in ISO8601 format.",
Fix description

2021-07-05 13:52 UTC, Subhajit97 commented on azure/table_azure_data_factory_pipeline.go
> +			// Standard columns
```suggestion
			},

			// Steampipe standard columns
```

2021-07-05 13:53 UTC, Subhajit97 commented on azure/table_azure_data_factory_pipeline.go
> +			{
```suggestion
			},

			// Azure standard columns
			{
```

2021-07-05 13:53 UTC, Subhajit97 commented on azure/table_azure_data_factory_pipeline.go
> +//// LIST FUNCTIONS ////
```suggestion
//// LIST FUNCTION
```

2021-07-05 13:53 UTC, Subhajit97 commented on azure/table_azure_data_factory_pipeline.go
> +			// d.StreamListItem(ctx, pipeline)
Remove unused codes
```suggestion
			d.StreamListItem(ctx, pipelineInfo{pipeline, *factoryInfo.Name})
```

2021-07-05 13:53 UTC, Subhajit97 commented on azure/table_azure_data_factory_pipeline.go
> +//// HYDRATE FUNCTIONS ////
```suggestion
//// HYDRATE FUNCTIONS
```

2021-07-05 13:54 UTC, Subhajit97 commented on azure/table_azure_data_factory_pipeline.go
> +
Add check for empty input

2021-07-12 11:33 UTC, Subhajit97 commented on azure/table_azure_data_factory_pipeline.go
> +				Transform:   transform.FromField("Etag"),
Not required
```suggestion
```

2021-07-12 11:38 UTC, Subhajit97 commented on azure/table_azure_data_factory_pipeline.go
> +				Type:        proto.ColumnType_JSON,
Is the type correct? 
Seems like the value is of type `integer`

2021-07-12 12:24 UTC, Subhajit97 commented on azure/table_azure_data_factory_pipeline.go
> +	return op, nil
```suggestion
	return nil, nil
```

2021-07-12 12:43 UTC, Subhajit97 approved these changes

2021-07-12 14:23 UTC, rajlearner17 requested changes
Let's add more example to check the Data Factory version in use or add the same to the example query as additional column. 
Query to check if encryption using CMK or not.

2021-07-15 05:33 UTC, rajlearner17 approved these changes
LGTM

2021-07-15 17:56 UTC, cbruno10 approved these changes

2021-07-15 17:58 UTC, merged