Add CHANGELOG for v0.24.0
turbot/steampipe-plugin-azure pull request #444
Opened 2022-02-09 15:00 UTC by misraved

2022-02-09 15:12 UTC, cbruno10 requested changes
Please see comments, thanks!

2022-02-09 15:12 UTC, cbruno10 commented on CHANGELOG.md
> +  As part of our deprecation process, we have now updated the above tables to not return any results, but   instead an error with the message to use the new tables instead. ([#443](https://github.com
```suggestion
  As part of our deprecation process, we have now updated the above tables to not return any results, but instead an error with the message to use the new tables instead. ([#443](https://github.com/turbot/steampipe-plugin-azure/pull/443))
```

2022-02-09 15:12 UTC, cbruno10 commented on CHANGELOG.md
> +_What's new?_
I think I'd put this under our Deprecation section instead, since it's not really a new feature

2022-03-23 11:20 UTC, misraved commented
Closing this PR since the deprecation of azure_ad * tables will be performed in a future release

2022-03-23 11:20 UTC, closed without merging