Fix column access_control inconsistent state in table azure_logic_app_workflow closes #484
turbot/steampipe-plugin-azure pull request #486
Opened 2022-05-06 11:04 UTC by ParthaI

# Integration test logs
<details>
  <summary>Logs</summary>
  
```
No env file present for the current environment:  staging 
 Falling back to .env config
No env file present for the current environment:  staging
customEnv TURBOT_TEST_EXPECTED_TIMEOUT undefined

SETUP: tests/azure_logic_app_workflow []

PRETEST: tests/azure_logic_app_workflow

TEST: tests/azure_logic_app_workflow
Running terraform
data.azurerm_client_config.current: Refreshing state...
data.null_data_source.resource: Refreshing state...
azurerm_resource_group.named_test_resource: Creating...
azurerm_resource_group.named_test_resource: Creation complete after 5s [id=/subscriptions/f5t37416-f95f-4771-bbb5-529d4c76ef46/resourceGroups/turbottest70107]
azurerm_logic_app_workflow.named_test_resource: Creating...
azurerm_logic_app_workflow.named_test_resource: Creation complete after 8s [id=/subscriptions/f5t37416-f95f-4771-bbb5-529d4c76ef46/resourceGroups/turbottest70107/providers/Microsoft.Logic/workflows/turbottest70107]

Warning: Deprecated Resource

  on variables.tf line 29, in data "null_data_source" "resource":
  29: data "null_data_source" "resource" {

The null_data_source was historically used to construct intermediate values to
re-use elsewhere in configuration, the same can now be achieved using locals

Apply complete! Resources: 2 added, 0 changed, 0 destroyed.

Outputs:

location = eastus
resource_aka = azure:///subscriptions/f5t37416-f95f-4771-bbb5-529d4c76ef46/resourceGroups/turbottest70107/providers/Microsoft.Logic/workflows/turbottest70107
resource_aka_lower = azure:///subscriptions/f5t37416-f95f-4771-bbb5-529d4c76ef46/resourcegroups/turbottest70107/providers/microsoft.logic/workflows/turbottest70107
resource_id = /subscriptions/f5t37416-f95f-4771-bbb5-529d4c76ef46/resourceGroups/turbottest70107/providers/Microsoft.Logic/workflows/turbottest70107
resource_name = turbottest70107
subscription_id = f5t37416-f95f-4771-bbb5-529d4c76ef46

Running SQL query: test-get-query.sql
[
  {
    "id": "/subscriptions/f5t37416-f95f-4771-bbb5-529d4c76ef46/resourceGroups/turbottest70107/providers/Microsoft.Logic/workflows/turbottest70107",
    "name": "turbottest70107",
    "region": "eastus",
    "resource_group": "turbottest70107",
    "subscription_id": "f5t37416-f95f-4771-bbb5-529d4c76ef46",
    "type": "Microsoft.Logic/workflows"
  }
]
✔ PASSED

Running SQL query: test-list-query.sql
[
  {
    "id": "/subscriptions/f5t37416-f95f-4771-bbb5-529d4c76ef46/resourceGroups/turbottest70107/providers/Microsoft.Logic/workflows/turbottest70107",
    "name": "turbottest70107",
    "type": "Microsoft.Logic/workflows"
  }
]
✔ PASSED

Running SQL query: test-not-found-query.sql
null
✔ PASSED

Running SQL query: test-turbot-query.sql
[
  {
    "akas": [
      "azure:///subscriptions/f5t37416-f95f-4771-bbb5-529d4c76ef46/resourceGroups/turbottest70107/providers/Microsoft.Logic/workflows/turbottest70107",
      "azure:///subscriptions/f5t37416-f95f-4771-bbb5-529d4c76ef46/resourcegroups/turbottest70107/providers/microsoft.logic/workflows/turbottest70107"
    ],
    "name": "turbottest70107",
    "title": "turbottest70107"
  }
]
✔ PASSED

POSTTEST: tests/azure_logic_app_workflow

TEARDOWN: tests/azure_logic_app_workflow

SUMMARY:

1/1 passed.
```
</details>

# Example query results
<details>
  <summary>Results</summary>
  
```
After the creation of logic app  workflow
> select access_control from azure_logic_app_workflow
+----------------+
| access_control |
+----------------+
| <null>         |
+----------------+
```

```
After configuring the access control to a IP range

> select access_control from azure_logic_app_workflow
+------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| access_control                                                                                                                                                   |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| {"actions":{"allowedCallerIpAddresses":[{"addressRange":"123.123.123.123/32"}]},"triggers":{"allowedCallerIpAddresses":[{"addressRange":"123.123.123.123/32"}]}} |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------+
```

```
After modifying the access control to any IP

> select access_control from azure_logic_app_workflow
+----------------+
| access_control |
+----------------+
| <null>         |
+----------------+
```

</details>

2022-05-06 13:17 UTC, cbruno10 requested changes
@ParthaI Please see comments - I didn't review any of the functionality though, so @bigdatasourav should still do that.

2022-05-06 13:17 UTC, cbruno10 commented on azure/table_azure_logic_app_workflow.go
> +// Access Control configuration for Any IP is comming as "{}" instead of nill if wea re not providing any IP in configuration
@ParthaI Ensuring we have proper spelling/grammar in comments is important as well, as these help us (and community members) read and understand the code. If you don't already have it installed, please install a spellchecker and grammarly plugin into VSCode, which should catch mistakes like these.

2022-05-31 07:24 UTC, bigdatasourav approved these changes
LGTM

2022-05-31 11:35 UTC, cbruno10 approved these changes

2022-06-01 06:40 UTC, merged