Add table azure_network_watcher_flow_log. Closes #60
turbot/steampipe-plugin-azure pull request #61
Opened 2021-03-23 11:37 UTC by Subhajit97

# Integration test logs
<details>
  <summary>Logs</summary>
  
```
Add passing integration test logs here
```
</details>

# Example query results
<details>
  <summary>Results</summary>
  

```sql
select
  name,
  enabled,
  network_watcher_name,
  target_resource_id
from
  azure_network_watcher_flow_log;
```
```
+------------------------------+---------+-----------------------+-------------------------------------------------------------------------------------------------------------------------------------------+
| name                         | enabled | network_watcher_name  | target_resource_id                                                                                                                        |
+------------------------------+---------+-----------------------+-------------------------------------------------------------------------------------------------------------------------------------------+
| test-nsg01-turbot_rg-flowlog | true    | NetworkWatcher_eastus | /subscriptions/d7245080-b4ae-4fe5-b6fa-2e71b3dae6c8/resourceGroups/turbot_rg/providers/Microsoft.Network/networkSecurityGroups/test-nsg01 |
+------------------------------+---------+-----------------------+-------------------------------------------------------------------------------------------------------------------------------------------+
```

### List of flow logs which are not enabled

```sql
select
  name,
  id,
  region,
  enabled
from
  azure_network_watcher_flow_log
where
  not enabled;
```
```
+------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------+---------+
| name                         | id                                                                                                                                                                                          | region | enabled |
+------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------+---------+
| test-nsg01-turbot_rg-flowlog | /subscriptions/d7245080-b4ae-4fe5-b6fa-2e71b3dae6c8/resourceGroups/networkwatcherrg/providers/Microsoft.Network/networkWatchers/NetworkWatcher_eastus/flowLogs/test-nsg01-turbot_rg-flowlog | eastus | false   |
+------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------+---------+
```

### List of flow logs for which retention period is less than 90 days

```sql
select
  name,
  region,
  enabled,
  flowlog_retention_days
from
  azure_network_watcher_flow_log
where
  enabled and flowlog_retention_days < 90;
```
```
+------------------------------+--------+---------+------------------------+
| name                         | region | enabled | flowlog_retention_days |
+------------------------------+--------+---------+------------------------+
| test-nsg01-turbot_rg-flowlog | eastus | true    | 0                      |
+------------------------------+--------+---------+------------------------+
```

### Storage account details used to store the flow log

```sql
select
  name,
  flowlog_format_type,
  storage_id
from
  azure_network_watcher_flow_log;
```
```
+------------------------------+---------------------+--------------------------------------------------------------------------------------------------------------------------------------------------+
| name                         | flowlog_format_type | storage_id                                                                                                                                       |
+------------------------------+---------------------+--------------------------------------------------------------------------------------------------------------------------------------------------+
| test-nsg01-turbot_rg-flowlog | JSON                | /subscriptions/d7245080-b4ae-4fe5-b6fa-2e71b3dae6c8/resourceGroups/turbot_rg/providers/Microsoft.Storage/storageAccounts/teststorageaccount23321 |
+------------------------------+---------------------+--------------------------------------------------------------------------------------------------------------------------------------------------+
```
</details>

2021-03-24 19:52 UTC, cbruno10 commented on azure/table_azure_network_watcher_flow_log.go
> +				Name:        "flowlog_retention_days",
Is there a reason we should include the word `flowlog` in the column name? Terraform has the fields as `retention_policy` and `days`, so a suitable name could be `retention_policy_days` (and `retention_policy_enabled` for the column below).

2021-03-24 19:55 UTC, cbruno10 commented on azure/table_azure_network_watcher_flow_log.go
> +				Name:        "flow_log_traffic_analytics_configuration",
Terraform uses `traffic_analytics`, so we can use the same name

2021-03-24 19:56 UTC, cbruno10 commented on azure/table_azure_network_watcher_flow_log.go
> +				Name:        "flowlog_version",
If there's no conflict with other columns, we should change this column name to `version`.

2021-03-24 19:58 UTC, cbruno10 commented on azure/table_azure_network_watcher_flow_log.go
> +				Name:        "flowlog_format_type",
Should this column name be reduced to `file_type`? There's no Terraform equivalent, but seems suitable based on the description.

2021-03-24 20:01 UTC, cbruno10 requested changes
Please see review comments, thanks!

2021-04-05 16:04 UTC, khushboo9024 commented on docs/tables/azure_network_watcher_flow_log.md
> +### List of flow logs for which retention period is less than 90 days
```suggestion
### List flow logs with retention period less than 90 days
```

2021-04-05 16:04 UTC, khushboo9024 commented on docs/tables/azure_network_watcher_flow_log.md
> +### List of flow logs which are not enabled
```suggestion
### List flow logs which are not enabled
```

2021-04-05 16:16 UTC, khushboo9024 commented on azure/table_azure_network_watcher_flow_log.go
> +				Name:        "provisioning_state",
can we keep `provisioning_state` below `network_watcher_name` column ?

2021-04-05 16:22 UTC, khushboo9024 commented on docs/tables/azure_network_watcher_flow_log.md
> +### Storage account details used to store the flow log
```suggestion
### Get storage account details used to store the flow log
```

2021-04-06 11:05 UTC, khushboo9024 approved these changes
LGTM

2021-04-07 07:20 UTC, rajmohanty17 approved these changes
LGTM

2021-04-26 19:27 UTC, cbruno10 approved these changes

2021-04-26 19:27 UTC, merged