Add table azure_postgresql_server. Closes #63
turbot/steampipe-plugin-azure pull request #64
Opened 2021-03-26 11:32 UTC by Subhajit97

# Integration test logs
<details>
  <summary>Logs</summary>
  
```
Add passing integration test logs here
```
</details>

# Example query results
<details>
  <summary>Results</summary>

### List servers for which Enforce SSL connection is enabled

```sql
select
  name,
  id,
  location,
  ssl_enforcement
from
  azure_postgresql_server
where
  ssl_enforcement = 'Enabled';
```  
```
+--------------------+---------------------------------------------------------------------------------------------------------------------------------------------+----------+-----------------+
| name               | id                                                                                                                                          | location | ssl_enforcement |
+--------------------+---------------------------------------------------------------------------------------------------------------------------------------------+----------+-----------------+
| testserver26032021 | /subscriptions/d7245080-b4ae-4fe5-b6fa-2e71b3dae6c8/resourceGroups/turbot_rg/providers/Microsoft.DBforPostgreSQL/servers/testserver26032021 | eastus   | Enabled         |
+--------------------+---------------------------------------------------------------------------------------------------------------------------------------------+----------+-----------------+
```

### List servers for which 'Allow access to Azure services' feature is disabled

```sql
select
  name,
  id,
  rule ->> 'Name' as rule_name,
  rule ->> 'Type' as rule_type,
  rule -> 'FirewallRuleProperties' ->> 'endIpAddress' as end_ip_address,
  rule -> 'FirewallRuleProperties' ->> 'startIpAddress' as start_ip_address
from
  azure_postgresql_server,
  jsonb_array_elements(firewall_rules) as rule
where
  rule ->> 'Name' = 'AllowAllWindowsAzureIps'
  and rule -> 'FirewallRuleProperties' ->> 'startIpAddress' = '0.0.0.0'
  and rule -> 'FirewallRuleProperties' ->> 'endIpAddress' = '0.0.0.0';
```
```
+--------------------+---------------------------------------------------------------------------------------------------------------------------------------------+-------------------------+-------------------------------------------------+----------------+------------------+
| name               | id                                                                                                                                          | rule_name               | rule_type                                       | end_ip_address | start_ip_address |
+--------------------+---------------------------------------------------------------------------------------------------------------------------------------------+-------------------------+-------------------------------------------------+----------------+------------------+
| testserver26032021 | /subscriptions/d7245080-b4ae-4fe5-b6fa-2e71b3dae6c8/resourceGroups/turbot_rg/providers/Microsoft.DBforPostgreSQL/servers/testserver26032021 | AllowAllWindowsAzureIps | Microsoft.DBforPostgreSQL/servers/firewallRules | 0.0.0.0        | 0.0.0.0          |
+--------------------+---------------------------------------------------------------------------------------------------------------------------------------------+-------------------------+-------------------------------------------------+----------------+------------------+
```

## List servers for which Active Directory Admin is not configured

```sql
select
  name,
  id,
  location
from
  azure_postgresql_server
where
  server_administrators is null;
```
```
+--------------------+---------------------------------------------------------------------------------------------------------------------------------------------+----------+
| name               | id                                                                                                                                          | location |
+--------------------+---------------------------------------------------------------------------------------------------------------------------------------------+----------+
| testserver26032021 | /subscriptions/d7245080-b4ae-4fe5-b6fa-2e71b3dae6c8/resourceGroups/turbot_rg/providers/Microsoft.DBforPostgreSQL/servers/testserver26032021 | eastus   |
+--------------------+---------------------------------------------------------------------------------------------------------------------------------------------+----------+
```

### List servers for which 'log_checkpoints' is set to 'OFF'

```sql
select
  name,
  configurations ->> 'Name' as configuration_name,
  configurations -> 'ConfigurationProperties' ->> 'value' as configuration_value
from
  azure_postgresql_server,
  jsonb_array_elements(server_configurations) as configurations
where
  configurations ->> 'Name' = 'log_checkpoints'
  and configurations -> 'ConfigurationProperties' ->> 'value' = 'OFF';
```
```
+--------------------+--------------------+---------------------+
| name               | configuration_name | configuration_value |
+--------------------+--------------------+---------------------+
| testserver26032021 | log_checkpoints    | OFF                 |
+--------------------+--------------------+---------------------+
```

### List servers for which 'log_retention_days' is greater than 3 days

```sql
select
  name,
  configurations ->> 'Name' as configuration_name,
  configurations -> 'ConfigurationProperties' ->> 'value' as configuration_value
from
  azure_postgresql_server,
  jsonb_array_elements(server_configurations) as configurations
where
  configurations ->> 'Name' = 'log_retention_days'
  and (configurations -> 'ConfigurationProperties' ->> 'value')::INTEGER > 3;
```
```
+--------------------+--------------------+---------------------+
| name               | configuration_name | configuration_value |
+--------------------+--------------------+---------------------+
| testserver26032021 | log_retention_days | 4                   |
+--------------------+--------------------+---------------------+
```
</details>

2021-04-05 17:14 UTC, khushboo9024 commented on azure/table_azure_postgresql_server.go
> +				Description: "Specifies the username of the Administrator for this server.",
```suggestion
				Description: "Specifies the username of the administrator for this server.",
```

2021-04-05 17:16 UTC, khushboo9024 commented on azure/table_azure_postgresql_server.go
> +				Name:        "user_visible_state",
can we put `user_visible_state` column `type`?

2021-04-05 17:18 UTC, khushboo9024 commented on azure/table_azure_postgresql_server.go
> +			},
order of standard columns should be title, tags, akas.

2021-04-05 18:50 UTC, khushboo9024 commented on azure/table_azure_postgresql_server.go
> +				Name:        "storage_profile_storage_mb",
column name should be `storage_mb` as per terraform.

2021-04-05 18:52 UTC, khushboo9024 commented on azure/table_azure_postgresql_server.go
> +				Name:        "storage_profile_storage_auto_grow",
column name should be `storage_auto_grow`.

2021-04-06 11:07 UTC, khushboo9024 approved these changes
LGTM

2021-04-07 06:57 UTC, rajmohanty17 commented on docs/tables/azure_postgresql_server.md
> +```
Add 2 more example which can be crucial 

1. In-transit encryption is enabled 
2. Geo-redundant backups are enabled

2021-04-07 06:57 UTC, rajmohanty17 requested changes
Added 2 more examples

2021-04-07 08:54 UTC, rajmohanty17 approved these changes
LGTM

2021-04-07 11:23 UTC, rajmohanty17 approved these changes
LGTM

2021-04-07 16:46 UTC, cbruno10 approved these changes

2021-04-07 16:46 UTC, merged