Add Azure monitor table. closes #38
turbot/steampipe-plugin-azure pull request #70
Opened 2021-03-31 06:48 UTC by bigdatasourav

# Integration test logs
<details>
  <summary>Logs</summary>
  
```
SETUP: tests/azure_log_alert []

PRETEST: tests/azure_log_alert

TEST: tests/azure_log_alert
Running terraform
azurerm_resource_group.named_test_resource: Creating...
azurerm_resource_group.named_test_resource: Creation complete after 3s [id=/subscriptions/d7245080-b4ae-4fe5-b6fa-2e71b3dae6c8/resourceGroups/turbottest86340]
azurerm_monitor_action_group.named_test_resource: Creating...
azurerm_storage_account.named_test_resource: Creating...
azurerm_monitor_action_group.named_test_resource: Still creating... [10s elapsed]
azurerm_storage_account.named_test_resource: Still creating... [10s elapsed]
azurerm_monitor_action_group.named_test_resource: Creation complete after 10s [id=/subscriptions/d7245080-b4ae-4fe5-b6fa-2e71b3dae6c8/resourceGroups/turbottest86340/providers/microsoft.insights/actionGroups/turbottest86340]
azurerm_storage_account.named_test_resource: Still creating... [20s elapsed]
azurerm_storage_account.named_test_resource: Still creating... [30s elapsed]
azurerm_storage_account.named_test_resource: Creation complete after 32s [id=/subscriptions/d7245080-b4ae-4fe5-b6fa-2e71b3dae6c8/resourceGroups/turbottest86340/providers/Microsoft.Storage/storageAccounts/turbottest86340]
azurerm_monitor_activity_log_alert.named_test_resource: Creating...
azurerm_monitor_activity_log_alert.named_test_resource: Still creating... [10s elapsed]
azurerm_monitor_activity_log_alert.named_test_resource: Creation complete after 11s [id=/subscriptions/d7245080-b4ae-4fe5-b6fa-2e71b3dae6c8/resourceGroups/turbottest86340/providers/microsoft.insights/activityLogAlerts/turbottest86340]

Warning: Deprecated Resource

The null_data_source was historically used to construct intermediate values to
re-use elsewhere in configuration, the same can now be achieved using locals

Apply complete! Resources: 4 added, 0 changed, 0 destroyed.

Outputs:

object_id = "959adfaa-3632-4f37-85a2-ef002bd72f9e"
resource_aka = "azure:///subscriptions/d7245080-b4ae-4fe5-b6fa-2e71b3dae6c8/resourceGroups/turbottest86340/providers/microsoft.insights/activityLogAlerts/turbottest86340"
resource_aka_lower = "azure:///subscriptions/d7245080-b4ae-4fe5-b6fa-2e71b3dae6c8/resourcegroups/turbottest86340/providers/microsoft.insights/activitylogalerts/turbottest86340"
resource_id = "/subscriptions/d7245080-b4ae-4fe5-b6fa-2e71b3dae6c8/resourceGroups/turbottest86340/providers/microsoft.insights/activityLogAlerts/turbottest86340"
resource_name = "turbottest86340"
subscription_id = "d7245080-b4ae-4fe5-b6fa-2e71b3dae6c8"
tenant_id = "cdffd708-7da0-4cea-abeb-0a4c334d7f64"

Running SQL query: test-get-query.sql
[
  {
    "id": "/subscriptions/d7245080-b4ae-4fe5-b6fa-2e71b3dae6c8/resourceGroups/turbottest86340/providers/microsoft.insights/activityLogAlerts/turbottest86340",
    "name": "turbottest86340",
    "region": "global",
    "type": "Microsoft.Insights/ActivityLogAlerts"
  }
]
✔ PASSED

Running SQL query: test-hydrate-query.sql
[
  {
    "akas": [
      "azure:///subscriptions/d7245080-b4ae-4fe5-b6fa-2e71b3dae6c8/resourceGroups/turbottest86340/providers/microsoft.insights/activityLogAlerts/turbottest86340",
      "azure:///subscriptions/d7245080-b4ae-4fe5-b6fa-2e71b3dae6c8/resourcegroups/turbottest86340/providers/microsoft.insights/activitylogalerts/turbottest86340"
    ],
    "name": "turbottest86340",
    "title": "turbottest86340"
  }
]
✔ PASSED

Running SQL query: test-list-query.sql
[
  {
    "id": "/subscriptions/d7245080-b4ae-4fe5-b6fa-2e71b3dae6c8/resourceGroups/turbottest86340/providers/microsoft.insights/activityLogAlerts/turbottest86340",
    "name": "turbottest86340"
  }
]
✔ PASSED

Running SQL query: test-not-found-query.sql
null
✔ PASSED

Running SQL query: test-turbot-query.sql
[
  {
    "akas": [
      "azure:///subscriptions/d7245080-b4ae-4fe5-b6fa-2e71b3dae6c8/resourceGroups/turbottest86340/providers/microsoft.insights/activityLogAlerts/turbottest86340",
      "azure:///subscriptions/d7245080-b4ae-4fe5-b6fa-2e71b3dae6c8/resourcegroups/turbottest86340/providers/microsoft.insights/activitylogalerts/turbottest86340"
    ],
    "name": "turbottest86340",
    "title": "turbottest86340"
  }
]
✔ PASSED

POSTTEST: tests/azure_log_alert

TEARDOWN: tests/azure_log_alert

SUMMARY:

1/1 passed.

SETUP: tests/azure_log_profile []

PRETEST: tests/azure_log_profile

TEST: tests/azure_log_profile
Running terraform
azurerm_resource_group.named_test_resource: Creating...
azurerm_resource_group.named_test_resource: Creation complete after 2s [id=/subscriptions/d7245080-b4ae-4fe5-b6fa-2e71b3dae6c8/resourceGroups/turbottest77670]
azurerm_eventhub_namespace.named_test_resource: Creating...
azurerm_storage_account.named_test_resource: Creating...
azurerm_eventhub_namespace.named_test_resource: Still creating... [10s elapsed]
azurerm_storage_account.named_test_resource: Still creating... [10s elapsed]
azurerm_eventhub_namespace.named_test_resource: Still creating... [20s elapsed]
azurerm_storage_account.named_test_resource: Still creating... [20s elapsed]
azurerm_eventhub_namespace.named_test_resource: Still creating... [30s elapsed]
azurerm_storage_account.named_test_resource: Still creating... [30s elapsed]
azurerm_storage_account.named_test_resource: Creation complete after 34s [id=/subscriptions/d7245080-b4ae-4fe5-b6fa-2e71b3dae6c8/resourceGroups/turbottest77670/providers/Microsoft.Storage/storageAccounts/turbottest77670]
azurerm_eventhub_namespace.named_test_resource: Still creating... [40s elapsed]
azurerm_eventhub_namespace.named_test_resource: Still creating... [50s elapsed]
azurerm_eventhub_namespace.named_test_resource: Still creating... [1m0s elapsed]
azurerm_eventhub_namespace.named_test_resource: Still creating... [1m10s elapsed]
azurerm_eventhub_namespace.named_test_resource: Creation complete after 1m17s [id=/subscriptions/d7245080-b4ae-4fe5-b6fa-2e71b3dae6c8/resourceGroups/turbottest77670/providers/Microsoft.EventHub/namespaces/turbottest77670]
azurerm_monitor_log_profile.named_test_resource: Creating...
azurerm_monitor_log_profile.named_test_resource: Still creating... [10s elapsed]
azurerm_monitor_log_profile.named_test_resource: Still creating... [20s elapsed]
azurerm_monitor_log_profile.named_test_resource: Still creating... [30s elapsed]
azurerm_monitor_log_profile.named_test_resource: Still creating... [40s elapsed]
azurerm_monitor_log_profile.named_test_resource: Still creating... [50s elapsed]
azurerm_monitor_log_profile.named_test_resource: Still creating... [1m0s elapsed]
azurerm_monitor_log_profile.named_test_resource: Creation complete after 1m7s [id=/subscriptions/d7245080-b4ae-4fe5-b6fa-2e71b3dae6c8/providers/microsoft.insights/logprofiles/turbottest77670]

Warning: Deprecated Resource

The null_data_source was historically used to construct intermediate values to
re-use elsewhere in configuration, the same can now be achieved using locals

Apply complete! Resources: 4 added, 0 changed, 0 destroyed.

Outputs:

object_id = "959adfaa-3632-4f37-85a2-ef002bd72f9e"
resource_aka = "azure:///subscriptions/d7245080-b4ae-4fe5-b6fa-2e71b3dae6c8/providers/microsoft.insights/logprofiles/turbottest77670"
resource_aka_lower = "azure:///subscriptions/d7245080-b4ae-4fe5-b6fa-2e71b3dae6c8/providers/microsoft.insights/logprofiles/turbottest77670"
resource_id = "/subscriptions/d7245080-b4ae-4fe5-b6fa-2e71b3dae6c8/providers/microsoft.insights/logprofiles/turbottest77670"
resource_name = "turbottest77670"
subscription_id = "d7245080-b4ae-4fe5-b6fa-2e71b3dae6c8"
tenant_id = "cdffd708-7da0-4cea-abeb-0a4c334d7f64"

Running SQL query: test-get-query.sql
[
  {
    "id": "/subscriptions/d7245080-b4ae-4fe5-b6fa-2e71b3dae6c8/providers/microsoft.insights/logprofiles/turbottest77670",
    "name": "turbottest77670"
  }
]
✔ PASSED

Running SQL query: test-hydrate-query.sql
[
  {
    "akas": [
      "azure:///subscriptions/d7245080-b4ae-4fe5-b6fa-2e71b3dae6c8/providers/microsoft.insights/logprofiles/turbottest77670",
      "azure:///subscriptions/d7 [...]

2021-04-01 12:50 UTC, Subhajit97 commented on azure/table_azure_location.go
> +		Name:        "azure_location sample test",
```suggestion
		Name:        "azure_location",
```

2021-04-01 12:50 UTC, Subhajit97 commented on azure/table_azure_diagnostic_setting.go
> +//// TABLE DEFINITION ////
```suggestion
//// TABLE DEFINITION
```

2021-04-01 12:50 UTC, Subhajit97 commented on azure/table_azure_diagnostic_setting.go
> +//// FETCH FUNCTIONS ////
```suggestion
//// FETCH FUNCTIONS
```

2021-04-01 12:52 UTC, Subhajit97 commented on azure/table_azure_diagnostic_setting.go
> +//// HYDRATE FUNCTIONS ////
```suggestion
//// HYDRATE FUNCTIONS
```

2021-04-01 12:52 UTC, Subhajit97 commented on azure/table_azure_diagnostic_setting.go
> +func getKeyDiagnosticSetting(ctx context.Context, d *plugin.QueryData, h *plugin.HydrateData) (interface{}, error) {
```suggestion
func getDiagnosticSetting(ctx context.Context, d *plugin.QueryData, h *plugin.HydrateData) (interface{}, error) {
```

2021-04-01 12:52 UTC, Subhajit97 commented on azure/table_azure_log_alert.go
> +//// TABLE DEFINITION ////
```suggestion
//// TABLE DEFINITION
```

2021-04-01 12:54 UTC, Subhajit97 commented on azure/table_azure_log_profile.go
> +//// TABLE DEFINITION ////
```suggestion
//// TABLE DEFINITION
```

2021-04-01 12:55 UTC, Subhajit97 commented on azure/table_azure_log_profile.go
> +func getKeyLogProfile(ctx context.Context, d *plugin.QueryData, h *plugin.HydrateData) (interface{}, error) {
```suggestion
func getLogProfile(ctx context.Context, d *plugin.QueryData, h *plugin.HydrateData) (interface{}, error) {
```

2021-04-01 12:56 UTC, Subhajit97 commented on azure-test/tests/azure_log_alert/variables.tf
> +  account_replication_type = "GRS"
```suggestion
  account_replication_type = "LRS"
```

2021-04-01 12:57 UTC, Subhajit97 commented on azure-test/tests/azure_log_profile/variables.tf
> +  account_replication_type = "GRS"
```suggestion
  account_replication_type = "LRS"
```

2021-04-01 12:57 UTC, Subhajit97 commented on azure-test/tests/azure_log_profile/variables.tf
> +
```suggestion
```

2021-04-01 12:57 UTC, Subhajit97 requested changes
Make suggested changes

2021-04-02 13:48 UTC, Subhajit97 commented on azure/table_azure_log_alert.go
> +	plugin.Logger(ctx).Trace("getKeyLogAlert")
```suggestion
	plugin.Logger(ctx).Trace("getLogAlert")
```

2021-04-02 13:48 UTC, Subhajit97 commented on azure/table_azure_log_profile.go
> +	plugin.Logger(ctx).Trace("getKeyLogProfile")
```suggestion
	plugin.Logger(ctx).Trace("getLogProfile")
```

2021-04-02 13:49 UTC, Subhajit97 commented on azure-test/tests/azure_diagnostic_setting/variables.tf
> +  account_replication_type = "GRS"
```suggestion
  account_replication_type = "LRS"
```

2021-04-02 13:51 UTC, Subhajit97 commented on azure-test/tests/azure_diagnostic_setting/variables.tf
> +  value = "azure://subscriptions/${var.azure_subscription}/providers/microsoft.insights/diagnosticsettings/${lower(var.resource_name)}"
No need to convert subscriptionID and name to lowercase, as the generated names are already in lowercase.
```suggestion
  value = "azure://subscriptions/${var.azure_subscription}/providers/microsoft.insights/diagnosticsettings/${var.resource_name}"
```

2021-04-02 13:51 UTC, Subhajit97 commented on azure-test/tests/azure_diagnostic_setting/variables.tf
> +}
Remove these outputs, if not used

2021-04-02 13:52 UTC, Subhajit97 commented on azure-test/tests/azure_log_alert/variables.tf
> +}
Remove, if not used

2021-04-02 13:53 UTC, Subhajit97 commented on azure-test/tests/azure_log_profile/variables.tf
> +}
Remove, if not used

2021-04-02 13:53 UTC, Subhajit97 commented on azure/plugin.go
> +			"azure_storage_blob":                tableAzureStorageBlob(ctx),
```suggestion
```

2021-04-02 14:00 UTC, Subhajit97 commented on docs/tables/azure_diagnostic_setting.md
> +  azure_diagnostic_setting;
Can we define this query to check for a specific category (i.e. Administrative, Alert, Policy, and Security)
Something like `Ensure Diagnostic Setting captures Alert, activities`?

2021-04-02 14:03 UTC, Subhajit97 requested changes
@bigdatasourav There are few more changes required. Please see comments, thanks!

2021-04-08 15:08 UTC, Subhajit97 commented on azure-test/tests/azure_log_alert/variables.tf
> +  default     = "d7245080-b4ae-4fe5-b6fa-2e71b3dae6c8"
```suggestion
  default     = "3510ae4d-530b-497d-8f30-53b9616fc6c1"
```

2021-04-08 15:08 UTC, Subhajit97 commented on azure-test/tests/azure_log_alert/variables.tf
> +
```suggestion
```

2021-04-08 15:09 UTC, Subhajit97 commented on azure-test/tests/azure_log_profile/variables.tf
> +  default     = "d7245080-b4ae-4fe5-b6fa-2e71b3dae6c8"
```suggestion
  default     = "3510ae4d-530b-497d-8f30-53b9616fc6c1"
```

2021-04-08 15:09 UTC, Subhajit97 commented on azure-test/tests/azure_log_profile/variables.tf
> +resource "azurerm_eventhub_namespace" "named_test_resource" {
```suggestion

resource "azurerm_eventhub_namespace" "named_test_resource" {
```

2021-04-08 15:09 UTC, Subhajit97 commented on azure/plugin.go
> +			"azure_compute_disk":                tableAzureComputeDisk(ctx),
Sort the list

2021-04-08 15:10 UTC, Subhajit97 commented on azure/table_azure_diagnostic_setting.go
> +			{
```suggestion
			
			// Azure standard columns
			{
```

2021-04-08 15:10 UTC, Subhajit97 commented on azure/table_azure_diagnostic_setting.go
> +func listDiagnosticSetting(ctx context.Context, d *plugin.QueryData, _ *plugin.HydrateData) (interface{}, error) {
```suggestion
func listDiagnosticSettings(ctx context.Context, d *plugin.QueryData, _ *plugin.HydrateData) (interface{}, error) {
```

2021-04-08 15:11 UTC, Subhajit97 commented on azure/table_azure_log_alert.go
> +			{
```suggestion
			
			// Azure standard columns
			{
```

2021-04-08 15:11 UTC, Subhajit97 commented on azure/table_azure_log_alert.go
> +func listLogAlert(ctx context.Context, d *plugin.QueryData, _ *plugin.HydrateData) (interface{}, error) {
```suggestion
func listLogAlerts(ctx context.Context, d *plugin.QueryData, _ *plugin.HydrateData) (interface{}, error) {
```

2021-04-08 15:11 UTC, Subhajit97 commented on azure/table_azure_log_profile.go
> +			{
```suggestion
			
			// Azure standard columns
			{
```

2021-04-08 15:12 UTC, Subhajit97 commented on azure/table_azure_log_profile.go
> +func listLogProfile(ctx context.Context, d *plugin.QueryData, _ *plugin.HydrateData) (interface{}, error) {
```suggestion
func listLogProfiles(ctx context.Context, d *plugin.QueryData, _ *plugin.HydrateData) (interface{}, error) {
```

2021-04-08 15:12 UTC, Subhajit97 commented on docs/tables/azure_diagnostic_setting.md
> +One or more destinations to send the logs. Current destinations include Log Analytics workspace, Event Hubs, and Azure Storage.
Can we update the description?

2021-04-08 15:13 UTC, Subhajit97 requested changes
@bigdatasourav There are few more changes required. Please see comments, thanks!

2021-04-09 11:33 UTC, Subhajit97 commented on azure/table_azure_diagnostic_setting.go
> +			},
Can we move the `DiagnosticSettings` properties at the top level?

2021-04-09 11:34 UTC, Subhajit97 commented on azure/table_azure_diagnostic_setting.go
> +	plugin.Logger(ctx).Trace("getKeyDiagnosticSetting")
```suggestion
	plugin.Logger(ctx).Trace("getDiagnosticSetting")
```

2021-04-09 11:34 UTC, Subhajit97 commented on azure/table_azure_diagnostic_setting.go
> +	}
Do we need this part?

2021-04-09 11:38 UTC, Subhajit97 commented on azure/table_azure_log_alert.go
> +			},
Move the `ActivityLogAlert` properties at the top level

2021-04-09 11:38 UTC, Subhajit97 commented on azure/table_azure_log_alert.go
> +	}
Do we need this check?

2021-04-09 11:40 UTC, Subhajit97 commented on docs/tables/azure_diagnostic_setting.md
> +### Ensure Diagnostic Setting captures Alert category
```suggestion
### List diagnostic settings that captures Alert category logs
```

2021-04-09 11:41 UTC, Subhajit97 commented on docs/tables/azure_log_alert.md
> +  )
Can we use `jsonb_array_elements` instead of using `jsonb_path_exists`?

2021-04-09 11:42 UTC, Subhajit97 requested changes
@bigdatasourav There are few more changes required.

2021-04-13 06:51 UTC, Subhajit97 commented on azure/table_azure_diagnostic_setting.go
> +				Name:        "Metrics",
```suggestion
				Name:        "metrics",
```

2021-04-13 06:54 UTC, Subhajit97 commented on azure/table_azure_log_profile.go
> +				Description: "Type of the resource",
```suggestion
				Description: "Type of the resource.",
```

2021-04-13 06:56 UTC, Subhajit97 commented on azure/table_azure_log_profile.go
> +				Description: "Resource location.",
```suggestion
				Description: "Specifies the name of the region, the resource is created at.",
```

2021-04-13 06:56 UTC, Subhajit97 commented on azure/table_azure_log_profile.go
> +				Description: "the resource id of the storage account to which you would like to send the Activity Log.",
```suggestion
				Description: "The resource id of the storage account to which you would like to send the Activity Log.",
```

2021-04-13 07:22 UTC, Subhajit97 approved these changes
LGTM

2021-04-15 07:58 UTC, rajmohanty17 approved these changes
LGTM

2021-04-15 08:34 UTC, rajmohanty17 approved these changes
LGTM

2021-04-22 18:52 UTC, cbruno10 approved these changes

2021-04-22 18:54 UTC, merged