Add Security Centre table. closes #36
turbot/steampipe-plugin-azure pull request #78
Opened 2021-04-02 12:29 UTC by bigdatasourav

# Integration test logs
<details>
  <summary>Logs</summary>
  
```
Add passing integration test logs here
```
</details>

# Example query results
<details>
  <summary>Results</summary>
  
```
Add example SQL query results here (please include the input queries as well)
```
</details>

2021-04-02 12:32 UTC, bigdatasourav commented
As discussed Integration test will not be performed for security center as default security setting can not change.

2021-04-02 14:04 UTC, Subhajit97 commented on azure/plugin.go
> +			"azure_security_center":             tableAzureSecurityCenter(ctx),
Sort the list

2021-04-02 14:04 UTC, Subhajit97 commented on azure/table_azure_security_center.go
> +//// TABLE DEFINITION ////
```suggestion
//// TABLE DEFINITION
```

2021-04-02 14:04 UTC, Subhajit97 commented on azure/table_azure_security_center.go
> +		Description: "Azure security Center",
```suggestion
		Description: "Azure Security Center",
```

2021-04-02 14:05 UTC, Subhajit97 commented on azure/table_azure_security_center.go
> +			},
Can we add descriptions for the columns?

2021-04-02 14:08 UTC, Subhajit97 commented on azure/table_azure_security_center.go
> +	PolicyClient.Authorizer = session.Authorizer
Can we add separate functions for each call? and finally combine the outputs and return from `listSecurityCenter`?

2021-04-02 14:13 UTC, Subhajit97 commented on docs/tables/azure_security_center.md
> +```
As per the query heading you should add a check for `email` field, otherwise it will always retrurn the whole contact object

2021-04-02 14:13 UTC, Subhajit97 commented on docs/tables/azure_security_center.md
> +```
Please verify this query

2021-04-02 14:15 UTC, Subhajit97 requested changes
@bigdatasourav There are some changes required. Please see comments, thanks!

2021-04-09 09:14 UTC, Subhajit97 commented on azure/plugin.go
> +			"azure_compute_disk":                tableAzureComputeDisk(ctx),
Sort the list

2021-04-09 09:17 UTC, Subhajit97 commented on azure/table_azure_security_center.go
> +			// Standard columns
```suggestion
			
			// Standard columns
```

2021-04-09 09:18 UTC, Subhajit97 commented on azure/table_azure_security_center.go
> +			{
```suggestion
			
			// Azure standard columns
			{
```

2021-04-09 10:50 UTC, Subhajit97 commented on azure/table_azure_security_center.go
> +	}
Can we move this to a separate function?

2021-04-09 10:51 UTC, Subhajit97 commented on azure/table_azure_security_center.go
> +	var settings []map[string]interface{}
Add a comment to describe the reason for handling the following case

2021-04-09 11:10 UTC, Subhajit97 commented on docs/tables/azure_security_center.md
> +  );
Can we use `jsonb_array_elements`?

2021-04-09 11:10 UTC, Subhajit97 commented on docs/tables/azure_security_center.md
> +  p -> 'properties' ->> 'autoProvision' as autoProvision
```suggestion
  p -> 'properties' ->> 'autoProvision' as auto_provision
```

2021-04-09 11:18 UTC, Subhajit97 commented on docs/tables/azure_security_center.md
> +### Ensure 'Additional email addresses' is configured with a security contact email
```suggestion
### Get security contact email configured for the subscription
```

2021-04-13 07:14 UTC, Subhajit97 commented on azure/table_azure_security_center.go
> +	}
Add this error handling block to `getPolicyDetails`

2021-04-13 07:14 UTC, Subhajit97 commented on azure/table_azure_security_center.go
> +	policy, err := getPolicyDetails(ctx, session, subscriptionID)
```suggestion
	policy := getPolicyDetails(ctx, session, subscriptionID)
```

2021-04-13 07:16 UTC, Subhajit97 commented on azure/table_azure_security_center.go
> +		"Id":               Id,
Do we need `ID`> or, it's just to create the aka?
If yes, add `Akas` instead.

2021-04-13 07:18 UTC, Subhajit97 requested changes
@bigdatasourav There are some small changes required, otherwise it look good.

2021-04-13 07:40 UTC, Subhajit97 approved these changes
LGTM

2021-04-15 08:25 UTC, rajmohanty17 approved these changes
LGTM

2021-04-22 18:59 UTC, cbruno10 commented
@bigdatasourav Are we unable to add integration tests for the security center resources?

2021-04-22 19:00 UTC, cbruno10 commented on azure/table_azure_security_center.go
> +func listSecurityCenter(ctx context.Context, d *plugin.QueryData, _ *plugin.HydrateData) (interface{}, error) {
@bigdatasourav Should this be `listSecurityCenters`? Or if we can't get more than 1 security center, is there a different function name we should use?

2021-04-22 19:00 UTC, cbruno10 requested changes
Please see comments, thanks!

2021-04-27 17:12 UTC, bigdatasourav commented on azure/table_azure_security_center.go
> +	policy, err := getPolicyDetails(ctx, session, subscriptionID)
Updated as discussed.

2021-04-27 17:12 UTC, bigdatasourav commented
Added Integration test log

2021-04-30 17:56 UTC, cbruno10 commented on azure/table_azure_security_center.go
> +				Name:        "auto_provisioning",
@LalitTurbot I think any of these columns that can return multiple items should be plural, though I'm not sure if we have a standard today on what we should end the column names with, e.g., auto_provisioning_settings, auto_provisioning_details, contacts, contact_settings, contact_details?

2021-05-03 06:34 UTC, bigdatasourav commented on azure/table_azure_security_center.go
> +				Name:        "auto_provisioning",
@cody all columns contain list of objects except the standard ones.
```
> select * from azure_security_center
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
| auto_provisioning                                                                                                                                                                                         
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
| [{"id":"/subscriptions/d7245080-b4ae-4fe5-b6fa-2e71b3dae6c8/providers/Microsoft.Security/autoProvisioningSettings/default","name":"default","properties":{"autoProvision":"Off"},"type":"Microsoft.Securit
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

2021-05-03 07:05 UTC, bigdatasourav commented on azure/table_azure_security_center.go
> +				Name:        "auto_provisioning",
updated

2021-05-04 05:43 UTC, Subhajit97 commented on azure/table_azure_security_center.go
> +				Name:        "auto_provisioning",
@bigdatasourav Please change the column names in tests and docs examples also.
Currently the docs examples and tests have the old column references.

2021-05-04 05:57 UTC, bigdatasourav commented on azure/table_azure_security_center.go
> +				Name:        "auto_provisioning",
updated

2021-05-05 18:54 UTC, cbruno10 commented
Closing this PR for now as it's be reworked into multiple tables as per https://github.com/turbot/steampipe-plugin-azure/issues/36#issuecomment-832210267. @bigdatasourav Feel free to re-open if the updates are in this branch, or open a new PR when ready, thanks!

2021-05-05 18:54 UTC, closed without merging