Add Kubernetes Cluster table. closes #44
turbot/steampipe-plugin-azure pull request #83
Opened 2021-04-08 10:21 UTC by sayan133

# Integration test logs
<details>
  <summary>Logs</summary>
  
```
No env file present for the current environment:  staging 
 Falling back to .env config
No env file present for the current environment:  staging
customEnv TURBOT_TEST_EXPECTED_TIMEOUT undefined

SETUP: tests/azure_kubernetes_cluster []

PRETEST: tests/azure_kubernetes_cluster

TEST: tests/azure_kubernetes_cluster
Running terraform
azurerm_resource_group.named_test_resource: Creating...
azurerm_resource_group.named_test_resource: Creation complete after 2s [id=/subscriptions/cd4401c4-3cc8-4565-a594-839c1e345f1e/resourceGroups/turbottest41797]
azurerm_kubernetes_cluster.named_test_resource: Creating...
azurerm_kubernetes_cluster.named_test_resource: Still creating... [10s elapsed]
azurerm_kubernetes_cluster.named_test_resource: Still creating... [20s elapsed]
azurerm_kubernetes_cluster.named_test_resource: Still creating... [30s elapsed]
azurerm_kubernetes_cluster.named_test_resource: Still creating... [40s elapsed]
azurerm_kubernetes_cluster.named_test_resource: Still creating... [50s elapsed]
azurerm_kubernetes_cluster.named_test_resource: Still creating... [1m0s elapsed]
azurerm_kubernetes_cluster.named_test_resource: Still creating... [1m10s elapsed]
azurerm_kubernetes_cluster.named_test_resource: Still creating... [1m20s elapsed]
azurerm_kubernetes_cluster.named_test_resource: Still creating... [1m30s elapsed]
azurerm_kubernetes_cluster.named_test_resource: Still creating... [1m40s elapsed]
azurerm_kubernetes_cluster.named_test_resource: Still creating... [1m50s elapsed]
azurerm_kubernetes_cluster.named_test_resource: Still creating... [2m0s elapsed]
azurerm_kubernetes_cluster.named_test_resource: Still creating... [2m10s elapsed]
azurerm_kubernetes_cluster.named_test_resource: Still creating... [2m20s elapsed]
azurerm_kubernetes_cluster.named_test_resource: Still creating... [2m30s elapsed]
azurerm_kubernetes_cluster.named_test_resource: Still creating... [2m40s elapsed]
azurerm_kubernetes_cluster.named_test_resource: Still creating... [2m50s elapsed]
azurerm_kubernetes_cluster.named_test_resource: Still creating... [3m0s elapsed]
azurerm_kubernetes_cluster.named_test_resource: Still creating... [3m10s elapsed]
azurerm_kubernetes_cluster.named_test_resource: Still creating... [3m20s elapsed]
azurerm_kubernetes_cluster.named_test_resource: Still creating... [3m30s elapsed]
azurerm_kubernetes_cluster.named_test_resource: Still creating... [3m40s elapsed]
azurerm_kubernetes_cluster.named_test_resource: Still creating... [3m50s elapsed]
azurerm_kubernetes_cluster.named_test_resource: Still creating... [4m0s elapsed]
azurerm_kubernetes_cluster.named_test_resource: Still creating... [4m10s elapsed]
azurerm_kubernetes_cluster.named_test_resource: Still creating... [4m20s elapsed]
azurerm_kubernetes_cluster.named_test_resource: Creation complete after 4m25s [id=/subscriptions/cd4401c4-3cc8-4565-a594-839c1e345f1e/resourcegroups/turbottest41797/providers/Microsoft.ContainerService/managedClusters/turbottest41797]

Warning: Deprecated Resource

The null_data_source was historically used to construct intermediate values to
re-use elsewhere in configuration, the same can now be achieved using locals

Apply complete! Resources: 2 added, 0 changed, 0 destroyed.

Outputs:

location = "westus"
object_id = "6af2b834-09c4-4c59-94a6-280711a6013a"
resource_aka = "azure:///subscriptions/cd4401c4-3cc8-4565-a594-839c1e345f1e/resourcegroups/turbottest41797/providers/Microsoft.ContainerService/managedClusters/turbottest41797"
resource_aka_lower = "azure:///subscriptions/cd4401c4-3cc8-4565-a594-839c1e345f1e/resourcegroups/turbottest41797/providers/microsoft.containerservice/managedclusters/turbottest41797"
resource_id = "/subscriptions/cd4401c4-3cc8-4565-a594-839c1e345f1e/resourcegroups/turbottest41797/providers/Microsoft.ContainerService/managedClusters/turbottest41797"
resource_name = "turbottest41797"
subscription_id = "cd4401c4-3cc8-4565-a594-839c1e345f1e"
tenant_id = "cdffd708-7da0-4cea-abeb-0a4c334d7f64"

Running SQL query: test-get-query.sql
[
  {
    "akas": [
      "azure:///subscriptions/cd4401c4-3cc8-4565-a594-839c1e345f1e/resourcegroups/turbottest41797/providers/Microsoft.ContainerService/managedClusters/turbottest41797",
      "azure:///subscriptions/cd4401c4-3cc8-4565-a594-839c1e345f1e/resourcegroups/turbottest41797/providers/microsoft.containerservice/managedclusters/turbottest41797"
    ],
    "id": "/subscriptions/cd4401c4-3cc8-4565-a594-839c1e345f1e/resourcegroups/turbottest41797/providers/Microsoft.ContainerService/managedClusters/turbottest41797",
    "identity": {
      "type": "SystemAssigned"
    },
    "location": "westus",
    "name": "turbottest41797",
    "rbac": false,
    "region": "westus",
    "resource_group": "turbottest41797",
    "sku": "{Name:Basic Tier:Free}",
    "subscription_id": "cd4401c4-3cc8-4565-a594-839c1e345f1e",
    "tags": {
      "foo": "bar"
    },
    "title": "turbottest41797",
    "type": "Microsoft.ContainerService/ManagedClusters"
  }
]
✔ PASSED

Running SQL query: test-list-query.sql
[
  {
    "id": "/subscriptions/cd4401c4-3cc8-4565-a594-839c1e345f1e/resourcegroups/turbottest41797/providers/Microsoft.ContainerService/managedClusters/turbottest41797",
    "name": "turbottest41797",
    "resource_group": "turbottest41797",
    "type": "Microsoft.ContainerService/ManagedClusters"
  }
]
✔ PASSED

Running SQL query: test-not-found-query.sql
null
✔ PASSED

Running SQL query: test-turbot-query.sql
[
  {
    "akas": [
      "azure:///subscriptions/cd4401c4-3cc8-4565-a594-839c1e345f1e/resourcegroups/turbottest41797/providers/Microsoft.ContainerService/managedClusters/turbottest41797",
      "azure:///subscriptions/cd4401c4-3cc8-4565-a594-839c1e345f1e/resourcegroups/turbottest41797/providers/microsoft.containerservice/managedclusters/turbottest41797"
    ],
    "name": "turbottest41797",
    "tags": {
      "foo": "bar"
    },
    "title": "turbottest41797"
  }
]
✔ PASSED

POSTTEST: tests/azure_kubernetes_cluster

TEARDOWN: tests/azure_kubernetes_cluster

SUMMARY:

1/1 passed.

```
</details>

# Example query results
<details>
  <summary>Results</summary>
  
```
Add example SQL query results here (please include the input queries as well)
```
</details>

2021-04-13 08:09 UTC, Paulami30 commented on azure/table_azure_kubernetes_cluster.go
> +//// TABLE DEFINITION ////
```suggestion
//// TABLE DEFINITION
```

2021-04-13 08:34 UTC, Paulami30 commented on docs/tables/azure_kubernetes_cluster.md
> +### List Kubernetes Clusters for a specific location
```suggestion
### List clusters for a specific location
```

2021-04-13 08:35 UTC, Paulami30 commented on docs/tables/azure_kubernetes_cluster.md
> +### List Kubernetes Clusters for a specific location
Remove service name from all the headings

2021-04-13 10:43 UTC, Paulami30 commented on azure/table_azure_kubernetes_cluster.go
> +				Description: "The friendly name that identifies the vault",
```suggestion
				Description: "The friendly name that identifies the vault.",
```

2021-04-26 09:33 UTC, khushboo9024 commented on azure/table_azure_kubernetes_cluster.go
> +				Name:        "sku",
`sku` column should be of type json , please check once.

2021-04-26 09:46 UTC, khushboo9024 commented on azure/table_azure_kubernetes_cluster.go
> +		resourceGroupName = strings.Split(string(*managedCluster.ID), "/")[4]
do we have the different response in list and get call ?

2021-04-26 09:50 UTC, khushboo9024 commented on azure/table_azure_kubernetes_cluster.go
> +				Type:        proto.ColumnType_JSON,
Json column should be at last.

2021-04-26 09:51 UTC, khushboo9024 requested changes
Please make suggested changes.

2021-04-30 09:08 UTC, Subhajit97 commented on azure/table_azure_kubernetes_cluster.go
> +//// TABLE DEFINITION ////
```suggestion
//// TABLE DEFINITION
```

2021-04-30 09:13 UTC, Subhajit97 commented on azure/table_azure_kubernetes_cluster.go
> +				// Hydrate:     getKubernetesCluster,
```suggestion
```

2021-04-30 09:13 UTC, Subhajit97 commented on azure/table_azure_kubernetes_cluster.go
> +			// Standard columns
```suggestion
			// Steampipe standard columns
```

2021-04-30 09:14 UTC, Subhajit97 commented on azure/table_azure_kubernetes_cluster.go
> +			{
```suggestion
			// Azure standard columns
			{
```

2021-04-30 09:14 UTC, Subhajit97 commented on azure/table_azure_kubernetes_cluster.go
> +//// HYDRATE FUNCTION
```suggestion
//// HYDRATE FUNCTIONS
```

2021-04-30 09:16 UTC, Subhajit97 commented on azure/table_azure_kubernetes_cluster.go
> +	resourceGroupName := d.KeyColumnQuals["resource_group"].GetStringValue()
Move this code blocks after creating the session

2021-04-30 09:19 UTC, Subhajit97 requested changes
@sayan133 There are some minor changes required. Please see comments, thanks!

2021-04-30 12:56 UTC, Subhajit97 commented on docs/tables/azure_kubernetes_cluster.md
> +  enable_rbac = 'false';
```suggestion
  enable_rbac;
```

2021-04-30 12:57 UTC, Subhajit97 commented on azure/table_azure_kubernetes_cluster.go
> +func getKubernetesCluster(ctx context.Context, d *plugin.QueryData, h *plugin.HydrateData) (interface{}, error) {
```suggestion
func getKubernetesCluster(ctx context.Context, d *plugin.QueryData, _ *plugin.HydrateData) (interface{}, error) {
```

2021-04-30 14:53 UTC, Subhajit97 approved these changes
LGTM

2021-05-03 08:04 UTC, rajmohanty17 requested changes
Can we add / extend the example to see the version / or check the latest version being used or not ?

2021-05-03 15:04 UTC, rajmohanty17 approved these changes
LGTM

2021-05-04 18:41 UTC, cbruno10 approved these changes

2021-05-04 18:41 UTC, merged